### ISSUE TITLE
Looks like the adapter isn't compatible with Casbin v2

### ISSUE THREAD

**Issue by chmorgan** [qiangmzsx/string-adapter#1]
`
import (
	"fmt"

	scas "github.com/qiangmzsx/string-adapter"

	"github.com/casbin/casbin/v2"
	"github.com/casbin/casbin/v2/model"
)

func main() {

	modelText := `
	[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub == r.obj.Owner`

	m := model.Model{}

	m.LoadModelFromText(modelText)

	line := `
	p, alice, /alice_data/*, (GET)|(POST)
	p, alice, /alice_data/resource1, POST
	p, data_group_admin, /admin/*, POST
	p, data_group_admin, /bob_data/*, POST
	g, alice, data_group_admin
	`
	sa := scas.NewAdapter(line)

	// Initialize a Gorm adapter and use it in a Casbin enforcer:
	// The adapter will use the MySQL database named "casbin".
	// If it doesn't exist, the adapter will create it automatically.
	// You can also use an already existing gorm instance with gormadapter.NewAdapterByDB(gormInstance)
	//a, _ := gormadapter.NewAdapter("mysql", "mysql_username:mysql_password@tcp(127.0.0.1:3306)/") // Your driver and data source.
	//	e, _ := casbin.NewEnforcer("examples/rbac_model.conf", a)
	e, _ := casbin.NewEnforcer(m, sa)

	// Or you can use an existing DB "abc" like this:
	// The adapter will use the table named "casbin_rule".
	// If it doesn't exist, the adapter will create it automatically.
	// a := gormadapter.NewAdapter("mysql", "mysql_username:mysql_password@tcp(127.0.0.1:3306)/abc", true)

	// Load the policy from DB.
	e.LoadPolicy()

	// Check the permission.
	if res, _ := e.Enforce("alice", "data1", "read"); res {
		fmt.Println("permitted")
	} else {
		fmt.Println("rejected")
	}

	// Modify the policy.
	// e.AddPolicy(...)
	// e.RemovePolicy(...)

	// Save the policy back to DB.
	e.SavePolicy()
}
`

`
[cmorgan@CHRISTOPHERs-MacBook-Pro casbintest]$ ./casbintest 
panic: interface conversion: *string_adapter.Adapter is not persist.Adapter: missing method LoadPolicy

goroutine 1 [running]:
github.com/casbin/casbin/v2.NewEnforcer(0xc0000f5f30, 0x2, 0x2, 0x0, 0x0, 0x0)
	/Users/cmorgan/go/pkg/mod/github.com/casbin/casbin/v2@v2.0.2/enforcer.go:88 +0x33f
main.main()
	/Users/cmorgan/projects/casbintest/main.go:46 +0xdf
`

**Comment by hsluoyz** [comment]
@qiangmzsx need fix.

**Comment by hsluoyz** [comment]
The author seems to be dormant these days. If you need a quick fix, you can fork it and fix it. Then maintain by yourself or request to put it into Casbin official org.

**Comment by qiangmzsx** [comment]
copy that

**Comment by qiangmzsx** [comment]
fix
