### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by Charles546** [qiangmzsx/string-adapter#4]
Our open source project https://github.com/honeydipper/honeydipper has a need to use your casbin adapter. However, our project has a license check step in CI. Our policy is to only use 3rd party libraries with permissive licenses, such as BSD, MIT etc.  We are trying to avoid APL, GPL etc. It would be really helpful if you can add a license to your repo, so we know how to proceed. Thanks! 

https://github.com/honeydipper/honeydipper/pull/318

**Comment by hsluoyz** [comment]
@qiangmzsx

**Comment by qiangmzsx** [comment]
Same as casbin, using apache v2.0

**Comment by hsluoyz** [comment]
@qiangmzsx please add a license file to the repo root folder. So it can show as:

![image](https://user-images.githubusercontent.com/3787410/93076900-a1601500-f6ba-11ea-9ae1-77ba5eb3a3fe.png)

**Comment by qiangmzsx** [comment]
done

**Comment by hsluoyz** [comment]
@qiangmzsx thanks! Please release a new version so he can use it in his PR.

See: https://github.com/honeydipper/honeydipper/pull/318/files#diff-37aff102a57d3d7b797f152915a6dc16R30

**Comment by qiangmzsx** [comment]
https://github.com/qiangmzsx/string-adapter/releases/tag/v2.1.0

**Comment by hsluoyz** [comment]
@Charles546 issue resolved.
