### ISSUE TITLE
string-adapter is broken when using latest github.com/casbin/casbin/v2 v2.48.0

### ISSUE THREAD

**Issue by dliulabs** [qiangmzsx/string-adapter#5]
m.LoadModelFromText(modelText) throws exception:

panic: interface conversion: *string_adapter.Adapter is not persist.Adapter: missing method LoadPolicy

**Comment by qiangmzsx** [comment]
> 

I tried the class library is no error reported, if you can, you'd better post the code.
I suspect you have a class library import problem.
You can also run \\github.com\qiangmzsx\string-adapter\adapter_test.goadapter_test.go`
