### ISSUE TITLE
Can Casbin be upgraded to latest version: v2.63?

### ISSUE THREAD

**Issue by rts-gordon** [qiangmzsx/string-adapter#6]
Hi there
  I use string-adapter in my project, but the Casbin version is a bit old. Can you please upgrade the Casbin to latest version v2.63? thank you.

**Comment by hsluoyz** [comment]
@rts-gordon can you make a PR to fix it?

**Comment by hsluoyz** [comment]
@qiangmzsx

**Comment by rts-gordon** [comment]
Hi @hsluoyz @qiangmzsx 

  I have made a PR for this upgrade: https://github.com/qiangmzsx/string-adapter/pull/7

Just a advice: I think the string-adapter is so simple, why not put this into Casbin main library? There is a build-in File-Adapter also.

 Cheers

**Comment by hsluoyz** [comment]
sounds OK to me. Can anyone make a PR to do it?

**Comment by qiangmzsx** [comment]
> sounds OK to me. Can anyone make a PR to do it?

Thank you for the PR：https://github.com/qiangmzsx/string-adapter/commit/7fdfc895ac51dc997afbc71df7d1a031da36889c

**Comment by rts-gordon** [comment]
@qiangmzsx 
  Would you like to give a Tag for this release? thank you.

**Comment by qiangmzsx** [comment]
> @qiangmzsx Would you like to give a Tag for this release? thank you.

Already created v2.2.0

**Comment by qiangmzsx** [comment]
> @qiangmzsx Would you like to give a Tag for this release? thank you.

Can you be the maintainer of this library?

**Comment by hsluoyz** [comment]
@qiangmzsx I can help maintain it. Please give me maintainer rights, thanks!

**Comment by rts-gordon** [comment]
@hsluoyz 
 Do you want to merge thus repo into Casbin man library? There will be no more inconsistencies between string-adaper and Casbin versions.

**Comment by hsluoyz** [comment]
@rts-gordon you can make a PR

**Comment by qiangmzsx** [comment]
> @qiangmzsx我可以帮助维护它。请给我维护者权限，谢谢！

Already sent you an invitation to become a maintainer

**Comment by rts-gordon** [comment]
@hsluoyz 
  OK, I will try this.

**Comment by hsluoyz** [comment]
Thanks!
